config/routes.rb
Myapp::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root to: 'logins#login'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"

  get "layoutsoptions/index"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/peity"
  get "graphs/sparkline"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"

  get "logins/search_results"
  get "logins/lockscreen"
  get "logins/invoice"
  get "logins/invoice_print"
  get "logins/login"
  get "logins/login_2"
  get "logins/register"
  get "logins/not_found_error"
  get "logins/internal_server_error"
  get "logins/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/jqgrid"

  get "gallery/basic_gallery"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appviews_controller.rb
class AppviewsController < ApplicationController
  def contacts
  end

  def profile
  end

  def projects
  end

  def project_detail
  end

  def file_manager
  end

  def calendar
  end

  def faq
  end

  def timeline
  end

  def pin_board
  end

end

app/controllers/cssanimations_controller.rb
class CssanimationsController < ApplicationController
  def index
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard_1
  end

  def dashboard_2
  end

  def dashboard_3
    @extra_class = "sidebar-content"
  end

  def dashboard_4
    render :layout => "layout_2"
  end

  def dashboard_4_1
  end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def basic_forms
  end

  def advanced
  end

  def wizard
  end

  def file_upload
  end

  def text_editor
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def basic_gallery
  end

  def bootstrap_carusela
  end

end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def flot
  end

  def morris
  end

  def rickshaw
  end

  def chartjs
  end

  def peity
  end

  def sparkline
  end

end

app/controllers/gridoptions_controller.rb
class GridoptionsController < ApplicationController
  def index
  end

end

app/controllers/layoutsoptions_controller.rb
class LayoutsoptionsController < ApplicationController
  def index
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def search_results
  end

  def lockscreen
    render :layout => "empty"
  end

  def invoice
  end

  def invoice_print
    render :layout => "empty"
  end

  def login
    render :layout => "empty"
  end

  def login_2
    render :layout => "empty"
  end

  def register
    render :layout => "empty"
  end

  def internal_server_error
    render :layout => "empty"
  end

  def empty_page
  end

  def not_found_error
    render :layout => "empty"
  end

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => e
      nil
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, :alert => "Access denied."
    end
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  def inbox
  end

  def email_view
  end

  def compose_email
  end

  def email_templates
  end

  def basic_action_email
    render :layout => false
  end

  def alert_email
    render :layout => false
  end

  def billing_email
    render :layout => false
  end

end

app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  def google_maps
  end

  def codee_ditor
  end

  def modal_window
  end

  def nestablelist
  end

  def validation
  end

  def notification
  end

  def timeline_second_version
  end

  def forum_view
  end

  def forum_post_view
  end

  def tree_view
  end

  def chat_view
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search_results
  end

  def lockscreen
    render :layout => "empty"
  end

  def invoice
  end

  def invoice_print
    render :layout => "empty"
  end

  def login
    render :layout => "empty"
  end

  def login_2
    render :layout => "empty"
  end

  def register
    render :layout => "empty"
  end

  def internal_server_error
    render :layout => "empty"
  end

  def empty_page
  end

  def not_found_error
    render :layout => "empty"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def static_tables
  end

  def data_tables
  end

  def jqgrid
  end

end

app/controllers/uielements_controller.rb
class UielementsController < ApplicationController
  def typography
  end

  def icons
  end

  def draggable_panels
  end

  def buttons
  end

  def tables_panels
  end

  def notifications_tooltips
  end

  def badges_labels_progress
  end

  def video
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/views/appviews/calendar.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-8">
        <h2>Calendar</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li>
            Extra pages
        </li>
        <li class="active">
            <strong>Calendar</strong>
        </li>
    </ol>
</div>
        </div>
<div class="wrapper wrapper-content">
<div class="row animated fadeInDown">
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Draggable Events</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#">Config option 1</a>
                        </li>
                        <li>
                            <a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div id='external-events'>
                    <p>Drag a event and drop into callendar.</p>
                    <div class='external-event navy-bg'>Go to shop and buy some products.</div>
                    <div class='external-event navy-bg'>Check the new CI from Corporation.</div>
                    <div class='external-event navy-bg'>Send documents to John.</div>
                    <div class='external-event navy-bg'>Phone to Sandra.</div>
                    <div class='external-event navy-bg'>Chat with Michael.</div>
                    <p class="m-t">
                        <input type='checkbox' id='drop-remove' class="i-checks" checked /> <label for='drop-remove'>remove after drop</label>
                    </p>
                </div>
            </div>
        </div>
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <h2>FullCalendar</h2> is a jQuery plugin that provides a full-sized, drag &amp; drop calendar like the one below. It uses AJAX to fetch events on-the-fly for each month and is
                easily configured to use your own feed format (an extension is provided for Google Calendar).
                <p>
                    <a href="http://arshaw.com/fullcalendar/" target="_blank">FullCalendar documentation</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Striped Table </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#">Config option 1</a>
                        </li>
                        <li>
                            <a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div id="calendar"></div>
            </div>
        </div>
    </div>
</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

    /* initialize the external events
     -----------------------------------------------------------------*/


    $('#external-events div.external-event').each(function () {

        // store data so the calendar knows to render an event upon drop
        $(this).data('event', {
            title: $.trim($(this).text()), // use the element's text as the event title
            stick: true // maintain when user navigates (see docs on the renderEvent method)
        });

        // make the event draggable using jQuery UI
        $(this).draggable({
            zIndex: 1111999,
            revert: true,      // will cause the event to go back to its
            revertDuration: 0  //  original position after the drag
        });

    });


    /* initialize the calendar
     -----------------------------------------------------------------*/
    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();

    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        editable: true,
        droppable: true, // this allows things to be dropped onto the calendar
        drop: function () {
            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
                // if so, remove the element from the "Draggable Events" list
                $(this).remove();
            }
        },
        events: [
            {
                title: 'All Day Event',
                start: new Date(y, m, 1)
            },
            {
                title: 'Long Event',
                start: new Date(y, m, d - 5),
                end: new Date(y, m, d - 2),
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d - 3, 16, 0),
                allDay: false,
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d + 4, 16, 0),
                allDay: false
            },
            {
                title: 'Meeting',
                start: new Date(y, m, d, 10, 30),
                allDay: false
            },
            {
                title: 'Lunch',
                start: new Date(y, m, d, 12, 0),
                end: new Date(y, m, d, 14, 0),
                allDay: false
            },
            {
                title: 'Birthday Party',
                start: new Date(y, m, d + 1, 19, 0),
                end: new Date(y, m, d + 1, 22, 30),
                allDay: false
            },
            {
                title: 'Click for Google',
                start: new Date(y, m, 28),
                end: new Date(y, m, 29),
                url: 'http://google.com/'
            }
        ],
    });


});

</script>

<% end %>



app/views/appviews/contacts.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Contacts</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li>
            App Views
        </li>
        <li class="active">
            <strong>Contacts</strong>
        </li>
    </ol>
</div>
        </div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-4">
        <div class="contact-box">
            <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
            <div class="col-sm-4">
                <div class="text-center">
                    <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a2.jpg') %>">
                    <div class="m-t-xs font-bold">Graphics designer</div>
                </div>
            </div>
            <div class="col-sm-8">
                <h3><strong>John Smith</strong></h3>
                <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                <address>
                    <strong>Twitter, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="clearfix"></div>
        </a>
    </div>
</div>
<div class="col-lg-4">
    <div class="contact-box">
        <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
        <div class="col-sm-4">
            <div class="text-center">
                <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
                <div class="m-t-xs font-bold">CEO</div>
            </div>
        </div>
        <div class="col-sm-8">
            <h3><strong>Alex Johnatan</strong></h3>
            <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
            <address>
                <strong>Twitter, Inc.</strong><br>
                795 Folsom Ave, Suite 600<br>
                San Francisco, CA 94107<br>
                <abbr title="Phone">P:</abbr> (123) 456-7890
            </address>
        </div>
        <div class="clearfix"></div>
    </a>
</div>
</div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a3.jpg') %>">
            <div class="m-t-xs font-bold">Marketing manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Monica Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a4.jpg') %>">
            <div class="m-t-xs font-bold">Sales manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Michael Zimber</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a5.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Sandra Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a6.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Janet Carton</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
            <div class="m-t-xs font-bold">CEO</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Alex Johnatan</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a2.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>John Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a3.jpg') %>">
            <div class="m-t-xs font-bold">Marketing manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Monica Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a4.jpg') %>">
            <div class="m-t-xs font-bold">Sales manager</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Michael Zimber</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a5.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Sandra Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a6.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Janet Carton</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>

</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a1.jpg') %>">
            <div class="m-t-xs font-bold">CEO</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>Alex Johnatan</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
<div class="col-lg-4">
<div class="contact-box">
    <a href="<%= url_for :controller => 'appviews', :action => 'profile' %>">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="img-circle m-t-xs img-responsive" src="<%= image_path('a2.jpg') %>">
            <div class="m-t-xs font-bold">Graphics designer</div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong>John Smith</strong></h3>
        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
        <address>
            <strong>Twitter, Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
    </div>
    <div class="clearfix"></div>
</a>
</div>
        </div>
        </div>
        </div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function () {

    $('.contact-box').each(function () {
        animationHover(this, 'pulse');
    });

});

</script>

<% end %>


app/views/logins/login.html.erb
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">Social inbox</h1>

            </div>


            <p>Login in. To see it in action.</p>
            <form class="m-t" role="form" action="#">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="">
                </div>
              <button class="btn btn-primary m-b-lg" type="button"><i class="fa fa-check"></i>&nbsp;Submit</button>

              <%=link_to 'Sign in',  signin_path, class:'btn btn-info btn-twitter m-b-lg fa fa-twitter' %>




              <a class="btn btn-success btn-facebook m-b-lg">
                <i class="fa fa-facebook"> </i> Sign in with Facebook
              </a>
              <a class="btn btn-danger btn-google-plus m-b-lg">
                <i class="fa fa-google-plus"> </i> Sign in with Google
              </a><br />

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-lg btn-white btn-block" href="<%= url_for :controller => 'logins', :action => 'register' %>">Create an account</a>
            </form>

        </div>
    </div>